<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Bnet.Extensions.Configuration.Consul</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
    <IsPackable>False</IsPackable>
    <TUnitImplicitUsings>false</TUnitImplicitUsings>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <NoWarn>$(NoWarn);TUnit0046</NoWarn>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\Bnet.Extensions.Configuration.Consul\Bnet.Extensions.Configuration.Consul.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="TUnit" Version="1.58.0" />
  </ItemGroup>

</Project>
