<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>Benet Oliver</Authors>
    <Company>Benet Oliver</Company>
    <Copyright>Copyright 2019 Winton. Modifications Copyright 2026 Benet Oliver.</Copyright>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <Description>Provides support for configuring .NET Core applications with Consul</Description>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <PackageId>Bnet.Extensions.Configuration.Consul</PackageId>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/benetv3/Bnet.Extensions.Configuration.Consul</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
    <PackageTags>.NET;Core;dotnetcore;ASP.NET;aspnetcore;configuration;consul;bnet</PackageTags>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/benetv3/Bnet.Extensions.Configuration.Consul</RepositoryUrl>
    <TargetFramework>net10.0</TargetFramework>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../LICENSE" Pack="true" PackagePath="" />
    <None Include="../../README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.9" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.300" PrivateAssets="All" />
  </ItemGroup>

</Project>